### PR TITLE
TICKET-138-NEW-RELEASE

### PR DESCRIPTION
**Pull request by Kushalbaj**
Add Footer styling and update links

### CODE REVIEW

**Review by sanjayguwaju — CHANGES_REQUESTED** [review]
```.custom--footer```  put this type of class name

**Review by smriteemanandhar — APPROVED** [review]
looks good

**Review by smriteemanandhar — APPROVED** [review]

**Comment by Kushalbaj** [comment]
DONE

**Comment by Kushalbaj** [comment]
> `.custom--footer` put this type of class name

DONE

**Review by sanjayguwaju — APPROVED** [review]

**Pull request merged**
